Tea 36
Mansur903/game.praktikum.yandex pull request #25
Opened 2024-03-17 10:36 UTC by Mansur903

### Добавил поддержку SSR в Express для prod и dev окружений

2024-03-18 15:59 UTC, V0L40K21 approved these changes

2024-03-19 16:46 UTC, IvanPeleshok requested changes
Добрый день!

Задачка выполнена хорошо, отлично потрудились

Есть небольшой вопрос

Хорошего дня :)

2024-03-19 16:46 UTC, IvanPeleshok commented on packages/client/src/App.tsx
> +		// <FullScreen handle={handle}>
Предлагаю оставлять содержательные комментарии о причине комментирования кода, либо удалять

2024-03-19 16:46 UTC, IvanPeleshok commented on packages/client/src/main.tsx
> -		<Provider store={store}>
Хранилище будете подключать в отдельной задаче?

2024-03-20 12:22 UTC, IvanPeleshok approved these changes
Всё замечательно, апрув
Хорошего дня :)

2024-03-21 21:06 UTC, closed without merging