[TEA-38] OAuth authentication has been added to the project
Mansur903/game.praktikum.yandex pull request #26
Opened 2024-03-18 20:57 UTC by xatepk

### Какую задачу решаем

Добавить OAuth-авторизацию в проект

2024-03-19 15:26 UTC, kate-lozovaya requested changes
Оставила комментарии. Посмотри их и призывай к ревью, как везде ответишь

2024-03-19 15:26 UTC, kate-lozovaya commented on packages/client/src/client.d.ts
> +	yandex: any
[Вопрос]
Точно ли тут нужен `any`? Может получится написать тип?

2024-03-19 15:26 UTC, kate-lozovaya commented on packages/client/src/lib/auth.ts
> +		if (name === YandexAuthErrorName.NotLoggedIn) {
[Предложение]
Можно в условии написать `err?.name`, чтобы не делать `@ts-ignore`. И когда используется какой-то `ignore`, лучше отмечать конкретное правило и причину для дизейбла

2024-03-19 15:26 UTC, kate-lozovaya commented on packages/client/src/lib/auth.ts
> +	search.append('redirect_uri', 'http://localhost:3000')
[Предложение]
Может вынести `'http://localhost:3000'` в константу? Чтобы можно было легко поменять значение

2024-03-19 15:26 UTC, kate-lozovaya commented on packages/client/src/lib/error.ts
> +		this.name = 'AppError'
[Предложение]
Может для разных кодов сделать разные `name` ошибок?

2024-03-19 15:26 UTC, kate-lozovaya commented on packages/client/src/lib/utils.ts
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any
[Исправление]
Не стоит выключать ТС для всего файла, лучше ставить дизейбл для конкретной строки и написать, пояснение, почему без `any` нельзя.
Вообще лучше от `any` избавиться

2024-03-19 15:26 UTC, kate-lozovaya commented on packages/client/src/pages/Login/Login.tsx
> +		const redirect_uri = 'http://localhost:3000'
Тут используется 'http://localhost:3000', это же значение есть и в `lib/auth.ts`, лучше сделать одну константу для `redirect_uri` и использовать ее везде

2024-03-19 15:26 UTC, kate-lozovaya commented on packages/client/src/routing/ProtectedRoute.tsx
> +					'https://ya-praktikum.tech/api/v2/oauth/yandex',
[Исправление]
Строка `'https://ya-praktikum.tech/api/v2/oauth/yandex'` используется в разных файлах. Нужно вынести в константу и использовать ее везде

2024-03-20 21:13 UTC, kate-lozovaya commented on packages/client/src/client.d.ts
> +	yandex: any
Тут нет ответа

2024-03-20 21:13 UTC, kate-lozovaya commented on packages/client/src/lib/auth.ts
> +		if (name === YandexAuthErrorName.NotLoggedIn) {
Тут нет ответа

2024-03-20 21:13 UTC, kate-lozovaya commented on packages/client/src/pages/Login/Login.tsx
> +			const {code} = err
Тут нет ответа

2024-03-20 21:13 UTC, kate-lozovaya reviewed
Не по всем комментариям увидела ответ. Напиши к ним ответ, пожалуйста

2024-03-22 19:43 UTC, xatepk commented on packages/client/src/pages/Login/Login.tsx
> +			const {code} = err
исправила

2024-03-22 19:43 UTC, xatepk commented on packages/client/src/lib/error.ts
> +		this.name = 'AppError'
решила оставить так

2024-03-22 19:45 UTC, xatepk commented on packages/client/src/lib/auth.ts
> +		if (name === YandexAuthErrorName.NotLoggedIn) {
исправила

2024-03-22 19:45 UTC, xatepk commented on packages/client/src/client.d.ts
> +	yandex: any
дополнила

2024-03-22 19:45 UTC, xatepk commented on packages/client/src/lib/auth.ts
> +		if (name === YandexAuthErrorName.NotLoggedIn) {
исправила

2024-03-23 10:47 UTC, kate-lozovaya reviewed
Не стоит использовать as, он просто отключает TS. Лучше честно проверить наличие поля или `instanceof`

2024-03-23 10:47 UTC, kate-lozovaya commented on packages/client/src/lib/auth.ts
> +		const {name} = err as typeof AppError
[Предложение]
`as` тоже просто отключает TS. Нужно убедиться, что `name` есть в `err` или  проверить `instanceof AppError`

2024-03-23 10:47 UTC, kate-lozovaya commented on packages/client/src/pages/Login/Login.tsx
> +			const {code} = err as AppError
[Предложение]
`as` просто отключает TS. Нужно убедиться, что `code ` есть в `err` или  проверить `instanceof AppError`

2024-03-23 11:02 UTC, xatepk commented on packages/client/src/lib/auth.ts
> +		const {name} = err as typeof AppError
Хорошо, я рассмотрю предложение.
По правилам практикума нельзя не принимать работу, если это пункт обозначен как Предложение, а не как Исправление

2024-03-23 11:02 UTC, xatepk commented on packages/client/src/pages/Login/Login.tsx
> +			const {code} = err as AppError
Хорошо, я рассмотрю предложение.
По правилам практикума нельзя не принимать работу, если это пункт обозначен как Предложение, а не как Исправление

2024-03-23 12:24 UTC, kate-lozovaya approved these changes
> По правилам практикума нельзя не принимать работу, если это пункт обозначен как Предложение, а не как Исправление
Кнопку принять нажимаю, когда задача готова к выкатке и вопросов/предложений/исправлений по коду нет. Когда я пишу комментарии, ожидаю диалога. Ты можешь быть в чем-то со мной несогласна и это можно обсудить.
А кнопка переделать - удобный механизм для отслеживания, чтобы сразу было видно, что можно приходить в ПР и смотреть его еще раз.

Сейчас прошу тебя убрать лишнюю вложенность. И после этого ПР можно будет вливать. Думаю, ты с этим отлично справишься, поэтому ставлю сразу апрув, чтобы не задерживать выкатку.

2024-03-23 12:24 UTC, kate-lozovaya commented on packages/client/src/lib/auth.ts
> +			if (err.name === YandexAuthErrorName.NotLoggedIn) {
[Исправление]
Нужно объединить через &&. Не стоит делать лишнюю вложенность без надобности, это усложняет код

2024-03-23 12:24 UTC, kate-lozovaya commented on packages/client/src/pages/Login/Login.tsx
> +			if (err instanceof AppError) {
[Исправление]
Не стоит делать дополнительную вложенность. Здесь можно сделать проверку на отрицание и сразу вернуть дефолтную ошибку

2024-04-07 16:00 UTC, merged